# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIr-Selz_2oJTU9n50YiAgYm9J-AglzF
"""

!pip install pandas scikit-learn sentence-transformers

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# تحميل الداتا
df = pd.read_csv("dataset.csv")

# تحويل label لـ class
def label_to_class(score):
    if score == 1:
        return 2
    elif score == 0.5:
        return 1
    else:
        return 0

df["target"] = df["score"].apply(label_to_class)

# تحميل embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# ------------------------
# Feature Engineering
# ------------------------
def extract_features(row):
    emb_correct = model.encode(row["correct_answer"], convert_to_tensor=True)
    emb_student = model.encode(row["student_answer"], convert_to_tensor=True)

    similarity = util.cos_sim(emb_correct, emb_student).item()

    length_ratio = len(row["student_answer"]) / (len(row["correct_answer"]) + 1)

    return [similarity, length_ratio]

# استخراج features
X = np.array(df.apply(extract_features, axis=1).tolist())
y = df["target"].values

# تقسيم الداتا
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# تدريب الموديل
clf = LogisticRegression()
clf.fit(X_train, y_train)

# تقييم
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

def evaluate_answer(question, correct, student):
    emb_correct = model.encode(correct, convert_to_tensor=True)
    emb_student = model.encode(student, convert_to_tensor=True)

    similarity = util.cos_sim(emb_correct, emb_student).item()
    score = round(similarity, 2)

    length_ratio = len(student) / (len(correct) + 1)
    features = np.array([[similarity, length_ratio]])

    pred = clf.predict(features)[0]

    if pred == 2:
        label = "Correct"
    elif pred == 1:
        label = "Partially Correct"
    else:
        label = "Wrong"

    return {
        "score": score,
        "label": label
    }

def calculate_final_result(scores):
    total_score = sum(scores)
    max_score = len(scores)

    percentage = (total_score / max_score) * 100

    if percentage < 50:
        level = "Beginner"
    elif percentage < 70:
        level = "Intermediate"
    else:
        level = "Advanced"

    return {
        "total_score": total_score,
        "percentage": round(percentage, 2),
        "level": level
    }

print(evaluate_answer(
    "What is HTML?",
    "HTML is the standard markup language for web pages.",
    "HTML is used to build web pages"
))

print(evaluate_answer(
    "What is HTML?",
    "HTML is the standard markup language for web pages.",
    "It is a programming language"
))

print(evaluate_answer(
    "What is HTML?",
    "HTML is the standard markup language for web pages.",
    "لغة لبناء صفحات الويب"
))

import joblib

joblib.dump(clf, "model.pkl")

print("✅ Model saved")

files.download("model.pkl")

def test():
    correct = "HTML is the standard markup language for web pages."
    student = "HTML is used to build web pages"

    emb1 = model.encode(correct, convert_to_tensor=True)
    emb2 = model.encode(student, convert_to_tensor=True)

    sim = util.cos_sim(emb1, emb2).item()
    print("Similarity:", sim)

test()

correct = 0
total = len(df)

for i, row in df.iterrows():
    result = evaluate_answer(
        row["question"],
        row["correct_answer"],
        row["student_answer"]
    )

    # نحول label لـ class
    pred = result["label"]

    if (
        (pred == "Correct" and row["score"] == 1) or
        (pred == "Partially Correct" and row["score"] == 0.5) or
        (pred == "Wrong" and row["score"] == 0)
    ):
        correct += 1

accuracy = correct / total

print(f"Accuracy: {accuracy:.2f}")

